// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MangaApi.Database.Migrations
{
    [DbContext(typeof(MangaContext))]
    [Migration("20230730093319_UpdateMangaSchema")]
    partial class UpdateMangaSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Manga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FinishedDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ReleaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Manga", "Manga");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f41ab0bf-b8e7-415c-b2e6-bc89f06e15b0"),
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            FinishedDate = new DateOnly(2014, 9, 18),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/e/e5/Tokyo_Ghoul_volume_1_cover.jpg",
                            Name = "Tokyo Ghoul",
                            ReleaseDate = new DateOnly(2011, 9, 8)
                        },
                        new
                        {
                            Id = new Guid("bf74f72b-d785-4a3b-b004-a1eeb79ab896"),
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            FinishedDate = new DateOnly(2014, 9, 18),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/e/e5/Tokyo_Ghoul_volume_1_cover.jpg",
                            Name = "Hunter x Hunter",
                            ReleaseDate = new DateOnly(1998, 3, 3)
                        },
                        new
                        {
                            Id = new Guid("3d509f29-9d00-4a0c-bcf9-27fde06406f7"),
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            FinishedDate = new DateOnly(2014, 10, 10),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/9/94/NarutoCoverTankobon1.jpg",
                            Name = "Naruto",
                            ReleaseDate = new DateOnly(1999, 9, 21)
                        },
                        new
                        {
                            Id = new Guid("f4749200-51b0-43a7-a12d-da7b30feb52a"),
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            FinishedDate = new DateOnly(2006, 5, 15),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/6/6f/Death_Note_Vol_1.jpg",
                            Name = "Death Note",
                            ReleaseDate = new DateOnly(2003, 12, 1)
                        },
                        new
                        {
                            Id = new Guid("04f33b42-b12b-4f4f-82d9-1918acdcb781"),
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            FinishedDate = new DateOnly(2000, 12, 1),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/db/Tomie_manga_cover.jpg",
                            Name = "Tomie",
                            ReleaseDate = new DateOnly(1987, 7, 1)
                        },
                        new
                        {
                            Id = new Guid("e43a59f4-b4c4-4c94-abdd-1756b7336de4"),
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            FinishedDate = new DateOnly(2020, 7, 20),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/6/6b/Haikyū_Volume_1.jpg",
                            Name = "Haikyuu!!",
                            ReleaseDate = new DateOnly(2012, 2, 20)
                        },
                        new
                        {
                            Id = new Guid("ee72803d-3d84-4e9a-9c63-fe38c2550611"),
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/5/5a/Boku_no_Hero_Academia_Volume_1.png",
                            Name = "My Hero Academia",
                            ReleaseDate = new DateOnly(2014, 7, 7)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
