on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: './appsettings.Development.json'
        env:
          Database.ConnectionString: ${{ secrets.DATABASE_CONNECTION_STRING }}
          OriginUrls: ${{ secrets.OriginUrls }}
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Test with dotnet
        run: dotnet test --no-build
      - name: Install EF Core Tools
        run: dotnet tool install -g dotnet-ef
      - name: Migrate Database
        run: dotnet ef database update
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Install Amazon Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools
      - name: Deploy to AWS
        run: dotnet lambda deploy-function